collections:
  - name: community.general
  - name: ansible.windows
  - name: community.vmware
  - name: vmware.vmware
  - name: amazon.aws
  - name: azure.azcollection
  - name: amazon.aws
  - name: community.aws
  - name: awx.awx
