- name: Ensure lvm2 present and show volumes
  hosts: ssh-test
  gather_facts: false
  become: true           # <- important
  tasks:
    - name: Install LVM2
      package:
        name: lvm2
        state: present

    # - name: Verify lock directory (created on boot, but ensure it exists)
    #   file:
    #     path: /run/lock/lvm
    #     state: directory
    #     owner: root
    #     group: root
    #     mode: '0755'

    - name: List LVs
      command: lvs --noheadings -o lv_name,vg_name,lv_size
      register: lvs_out

    - debug:
        var: lvs_out.stdout_lines
