---
- name: Test full_payload from EDA
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Show full_payload value
      ansible.builtin.debug:
        msg: "{{ ansible_eda.event.payload.message }}"
