---
- name: Test full_payload from EDA
  hosts: localhost
  gather_facts: false
  vars:
    my_message: "{{ ansible_eda.event.payload.message }}"

  tasks:

    - name: Show full_payload value
      ansible.builtin.debug:
        msg: "{{ my_message }}"
