---
- name: Test full_payload from EDA
  hosts: localhost
  gather_facts: false
  vars:
    my_message: "{{ ansible_eda.event.payload.message }}"
    # first_part1: "{{ my_message.split(' ')[0] }}"
    # first_part2: "{{ my_message.split(' ')[1] }}"
    # first_part3: "{{ my_message.split(' ')[2] }}"
    # first_part4: "{{ my_message.split(' ')[3] }}"
    target_user_id: "{{ my_message | regex_search('[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}') }}"
    ritm_number: "{{ my_message | regex_search('RITM\\d+') }}"
   # first_part5: "{{ my_message.split(' ')[4] }}"

  tasks:

    - name: Print the email address
      ansible.builtin.debug:
        msg: "Email Address: {{ target_user_id }}"

    - name: Print the SNOW number
      ansible.builtin.debug:
        msg: "SNOW No.: {{ ritm_number }}"
