---
- name: "Definitive Timezone Diagnostic Playbook"
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
    - name: "Print payload"
      ansible.builtin.debug:
        msg: "payload: {{ full_payload }}"
