---
- name: Export all assets
  hosts: localhost
  collections:
    - awx.awx
  vars_files:
    - ../var_files/platform-info.yml
  environment:
    AWXKIT_API_BASE_PATH: "/api/controller/"
  
  tasks: 
  - name: Export selected assets from AAP 2.5

    ansible.controller.export:
      controller_host: "{{ gateway_hostname }}"
      controller_username: "{{ gateway_username }}"
      controller_password: "{{ gateway_password }}"
      validate_certs: false
      # pick what you need; avoid "all" at first
      # organizations: ["all"]
      # users: ["all"]
      credentials: ["all"]
      projects: ["all"]
      job_templates: ["all"]
    environment:
      AWXKIT_API_BASE_PATH: "/api/controller/"
  
  # tasks:
  #   - name: Export all assets
  #     awx.awx.export:
  #       all: true
  #       tower_username: admin
  #       tower_password: "{{ gateway_password }}"
  #       tower_host: "{{ gateway_hostname }}"