---
- name: Export all assets
  hosts: localhost
  collections:
    - awx.awx
  vars_files:
    - ../var_files/platform-info.yml
  environment:
    AWXKIT_API_BASE_PATH: "/api/controller/"
  tasks:
    - name: Export all assets
      awx.awx.export:
        all: true
        tower_username: admin
        tower_password: "{{ gateway_password }}"
        tower_host: "{{ gateway_hostname }}"