# export-selected.yml
- hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller
  vars_files:
    - ../var_files/platform-info.yml
  vars:
    controller_host: "{{ gateway_hostname }}"
    controller_oauthtoken: "{{ pat }}"    # use a Personal Access Token
    validate_certs: false             # set true if your cert chain is trusted
  tasks:
    - name: Export JTs, Projects, Credentials
      ansible.controller.export:
        job_templates: 'all'          # or ["JT A","JT B"]
        projects: 'all'               # or ["Proj A","Proj B"]
        credentials: 'all'            # or a list of names
        validate_certs: "{{ validate_certs }}"
      register: out

    - name: Save to YAML
      copy:
        content: "{{ out.assets | to_nice_yaml }}"
        dest: aap-export.yml
