---
- name: Playbook for testing
  hosts: ec2-18-190-156-41.us-east-2.compute.amazonaws.com
  gather_facts: false
  vars:
    gateway_validate_certs: false
  vars_files:
    - ../var_files/orgs.yml
    - ../var_files/teams.yml
    - ../var_files/projects.yml
    - ../var_files/job_templates.yml
    - ../var_files/platform-info.yml
  roles:
    - ../../roles/manage-aap-config
  