---
- name: Playbook for testing
  hosts: 192.168.64.5
  gather_facts: false
  vars:
    controller:
      host: '{{ lookup("env", "CONTROLLER_HOST") }}'
      username: '{{ lookup("env", "CONTROLLER_USERNAME") }}'
      password: '{{ lookup("env", "CONTROLLER_PASSWORD") }}'
  
  tasks:
    - name: Create organization
      ansible.controller.organization:
        controller_host: 192.168.64.5
        controller_username: admin
        controller_password: admin
        name: "Foo"
        description: "Foo bar organization"
        state: present
    
    - name: Create Template
      ansible.controller.team:
        name: Dev Template
        description: Developer team - Dev Env
        organization: Foo
        state: present


    - name: Creating Removal Job Template with Survey
      ansible.controller.job_template:
        name: Remove Terraform Manifest AWS
        organization: Default
        job_type: run
        inventory: Demo Inventory
        project: aws-tf
        execution_environment: tr
        playbook: terraform_aws_destroy.yml
        credentials:
          - aws-ec2
          - aws-tf-keys
        state: present
        extra_vars:
          pah_pass: "{{ lookup('env', 'PAH_PASS') }}"
          # - cert_key_file: "\"{{ lookup('env', 'CERT_KEY_FILE') }}\""
          # - mytoken: "\"{{ lookup('env', 'GIT_TOKEN') }}\""
          # - username: "\"{{ lookup('env', 'GIT_USERNAME') }}\""
       # survey_spec: "{{ slurpfile['content'] | b64decode }}"
       # survey_enabled: true
