---
- name: Playbook for testing
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../var_files/orgs.yml
  
  tasks:
    - name: Create organization
      ansible.controller.organization:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present
      loop: "{{ controller_organizations }}"
    
    - name: Create Team
      ansible.controller.team:
        name: Dev Template
        description: Developer team - Dev Env
        organization: Foo
        state: present


    - name: Creating Removal Job Template with Survey
      ansible.controller.job_template:
        name: Remove Terraform Manifest AWS
        organization: Default
        job_type: run
        inventory: Demo Inventory
        project: ansible-terraform
        execution_environment: tf
        playbook: terraform_aws_destroy.yml
        state: present
