---
- name: Playbook for testing
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../var_files/orgs.yml
    - ../var_files/teams.yml
    - ../var_files/projects.yml
    - ../var_files/job_templates.yml
  
  tasks:
    - name: Create organizations
      ansible.controller.organization:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present
      loop: "{{ controller_organizations }}"
    
    - name: Create Teams
      ansible.controller.team:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        state: present
      loop: "{{ controller_teams }}"

    - name: Create Projects
      ansible.controller.project:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        organization: "{{ item.organization }}"
        scm_branch: "{{ item.scm_branch }}"
        scm_clean: "{{ item.scm_clean }}"
        scm_delete_on_update: "{{ item.scm_delete_on_update }}"
        scm_type: "{{ item.scm_type }}"
        scm_update_on_launch: "{{ item.scm_update_on_launch }}"
        scm_url: "{{ item.scm_url }}"
      loop: "{{ controller_projects }}"

    - name: Creating Job Templates
      ansible.controller.job_template:
        name: "{{ item.name }}"
        organization: "{{ item.organization }}"
        job_type: "{{ item.job_type }}"
        inventory: "{{ item.inventory }}"
        project: "{{ item.project }}"
        execution_environment: "{{ item.execution_environment }}"
        playbook: "{{ item.playbook }}"
        credentials: "{{ item.credentials }}"
        state: present
      loop: "{{ controller_templates }}"
