- name: Playbook for testing
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Create organization
      ansible.controller.organization:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present