---
- name: Playbook for testing
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../var_files/orgs.yml
    - ../var_files/teams.yml
    - ../var_files/projects.yml
    - ../var_files/job_templates.yml
  
  tasks:

    - name: Delete Job Templates
      ansible.controller.job_template:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ controller_templates }}"
    
    - name: Delete Projects
      ansible.controller.project:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ controller_projects }}"

    - name: Delete Teams
      ansible.controller.team:
        name: "{{ item.name }}"
        organization: "{{ item.organization }}"
        state: absent
      loop: "{{ controller_teams }}"

    - name: Delete organizations
      ansible.controller.organization:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ controller_organizations }}"
