---
- name: 3. Create and Configure the Oracle Database
  hosts: oracle_servers
  become: yes
  become_user: oracle
  vars:
    oracle_home: "/u01/app/oracle/product/19.0.0/dbhome_1"
    dbca_rsp_file: "dbca.rsp" # This file should be in a 'templates' folder

  tasks:
    - name: Template the DBCA response file
      ansible.builtin.template:
        src: "{{ dbca_rsp_file }}.j2"
        dest: "/home/oracle/{{ dbca_rsp_file }}"
        owner: oracle
        group: oinstall

    - name: Create the database using DBCA
      ansible.builtin.command:
        cmd: >
          {{ oracle_home }}/bin/dbca -silent -createDatabase
          -responseFile /home/oracle/{{ dbca_rsp_file }}
      # This can take a long time, adjust timeout if needed
      async: 1800 # 30 minutes
      poll: 60

    - name: Start the listener
      ansible.builtin.command: "{{ oracle_home }}/bin/lsnrctl start"
      environment:
        ORACLE_HOME: "{{ oracle_home }}"

    - name: Example - Create a new tablespace
      community.oracle.oracle_sql:
        username: "SYS"
        password: "YourSysPassword" # Use Ansible Vault
        service_name: "YOURDB.yourdomain.com"
        mode: "sysdba"
        script: "CREATE TABLESPACE users DATAFILE '/u01/app/oracle/oradata/YOURDB/users01.dbf' SIZE 100M;"
      # This task is just an example of post-configuration