---
- name: Create VM from an Image Service image
  hosts: localhost
  connection: local
  gather_facts: false
  collections: [nutanix.ncp]

  vars:
    nutanix_host: "{{ lookup('env','NTNX_HOST') }}"
    nutanix_username: "{{ lookup('env','NTNX_USER') }}"
    nutanix_password: "{{ lookup('env','NTNX_PASS') }}"
    validate_certs: false

    vm_name: "oracle-db-vm"
    vm_cpu: 4
    vm_mem_gb: 16
    network_name: "Prod-Network"
    image_name: "rhel-8.8-gold"
    disk_size_gb: 100              # optional extra data disk

  tasks:
    - name: Ensure VM present and powered on
      nutanix.ncp.ntnx_vms:
        state: present
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        memory_mb: "{{ vm_mem_gb * 1024 }}"
        num_vcpus: "{{ vm_cpu }}"
        num_cores_per_vcpu: 1
        networks:
          - is_connected: true
            network_name: "{{ network_name }}"
        disks:
          - image_name: "{{ image_name }}"
            disk_type: "DISK"
        power_state: on

    - name: (Optional) Attach additional empty data disk for Oracle
      nutanix.ncp.ntnx_vms:
        state: present
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vm_name }}"
        disks:
          - disk_type: "DISK"
            disk_size_mib: "{{ disk_size_gb * 1024 }}"
        power_state: on
