---
- name: Mount NFS 
  hosts: "{{ target | default('oracle_vms') }}"
  become: yes
  gather_facts: yes

  vars:
    
    nfs_server: "nfs01.example.com"
    nfs_export: "/exports/software"
    nfs_mount_point: "/mnt/sw"
    nfs_version: "4.1"                       
    nfs_opts_extra: ""                       
    nfs_state: "mounted"                     

  pre_tasks:
    - name: Ensure NFS client utilities are installed
      ansible.builtin.package:
        name: nfs-utils
        state: present

    - name: Create mount point
      ansible.builtin.file:
        path: "{{ nfs_mount_point }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

  tasks:
    - name: Build NFS mount options
      ansible.builtin.set_fact:
        nfs_opts_final: >-
          rw,hard,intr,_netdev,noatime,nfsvers={{ nfs_version }}
          {{ (',' + nfs_opts_extra) if nfs_opts_extra|length > 0 else '' }}

    - name: Mount and persist NFS
      ansible.posix.mount:
        path: "{{ nfs_mount_point }}"
        src: "{{ nfs_server }}:{{ nfs_export }}"
        fstype: nfs
        opts: "{{ nfs_opts_final | replace(' ', '') }}"
        state: "{{ nfs_state }}"
