- name: Provision EC2
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: us-east-2
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: my-ec2-instance
        key_name: eda_key
        instance_type: t3.micro
        image_id: ami-0f70b01eb0d5c5caa
        region: us-east-2
        security_groups: sg-085986a21981ac485
        vpc_subnet_id: subnet-0e872e25395b17d20
        network_interfaces:
          - assign_public_ip: true
            
        wait: true
      register: ec2_out

    - name: Pick the first (or only) instance
      ansible.builtin.set_fact:
        new_instance: "{{ ec2_out.instances[0] }}"

    - name: Show instance details
      ansible.builtin.debug:
        var: new_instance

# ansible.builtin.set_stats saves the paramert value globaly during 
# the workflow execution. 
    - name: Save new instance DNS
      ansible.builtin.set_stats:
        data:
          new_ec2_dns: "{{ ec2_out.instances[0].public_dns_name }}"
