---
- name: Listen for events on a webhook
  hosts: localhost
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"
      actions:
        - run_job_template:
            name: Demo_Job_Template
            organization: Default
<<<<<<< HEAD
            job_args:
              extra_vars:
                taiseer: "{{ event.payload }}"
=======
            # execution_strategy: run_all
  #  - name: Rule 2
  #    condition: event.payload.test == "Ansible"
  #    actions:
  #      - run_job_template:
  #          name: Demo_Job_Template_2
  #          organization: Default
>>>>>>> df44ccd88e2ddf921a3ffabc5b63af1b766ec44a
