- name: React to webhook events
  hosts: all
  sources:
    - name: webhook_source
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run job template on payload defined
      condition: event.payload.message == "Demo"
      action:
        run_job_template:
          name: Demo_Job_Template