---
- name: Minimal Test Rulebook
  hosts: localhost
  execution_strategy: parallel
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Match and pass var
      condition: true
      actions:
        - run_job_template:
            name: Demo_Job_Template
            organization: Default
            # job_args:
            #   extra_vars:
            #     full_payload: "{{ event.payload.message }}"
