---
- name: Listen for events on a webhook
  hosts: localhost
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible is super cool"
      actions:
        - run_job_template:
            name: Demo_Job_Template
            organization: Default
            job_args:
              extra_vars:
                taiseer: "{{ event.payload }}"
