- name: Webhook Events
  hosts: localhost
  sources:
    - name: Git Hub
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Git Hub Commit
      condition: event.meta.headers is defined
      action:
        run_job_template:
          name: gitops
          organization: Default