- name: Webhook Events
  hosts: localhost
  sources:
    - name: Git Hub
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.meta.headers.X_Gitea_Event == "push"
      action:
        run_job_template:
          name: aap-config-cr
          organization: Default